### ISSUE TITLE
[GSoC 2021] Revamping the UI

### ISSUE THREAD

**Issue by ruddi10** [bench-routes/dashboard#2]
Tasks and milestones that need to be completed -

- [x] Updating Readme
- [x] Updating boilerplate #3 
- [x] Adding Custom theme #3 
- [x] Wriiting reusable fetch service #6 
- [x] Add MachineSelector component #7 
- [x] Add TimeQuerier component #9 
- [x] Add RouteSelector component #17 
- [x] Add Graph Component #20 
- [x] Migrate the dashboard from mock API to backend #21 
- [x] Writting tests #4 
- [x] Add documentation #28
